controller:
  serviceAccount:
    create: true
    name: "jenkins-controller"

  rbac:
    create: true
    readSecrets: true

  image:
    repository: "dubithal/k8s-jenkins-controller"
    tag: "latest"

  installPlugins: []
  initializeOnce: true
  overwritePluginsFromImage: false

  usePodSecurityContext: true
  runAsUser: 1000
  fsGroup: 1000

  persistence:
    defaultVolumePermissions:
      enabled: true   

  serviceType: NodePort
  nodePort: 30080

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 10
    periodSeconds: 15

persistence:
  enabled: true
  size: "8Gi"
  storageClass: "local-path"
