controller:
  admin:
    Username: admin
    Password: admin

  serviceType: NodePort
  nodePort: 30080

  # Point to your custom image on DockerHub
  image:
    repository: "dubithal/k8s-jenkins-controller" 
    tag: "latest"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean
