controller:
  serviceAccount:
    create: true
    name: "jenkins-controller"

  admin:
    Username: admin
    Password: admin

  serviceType: NodePort
  nodePort: 30080

  image:
    repository: "dubithal/k8s-jenkins-controller"
    tag: "latest"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean
  readinessProbe:
    initialDelaySeconds: 120 
    timeoutSeconds: 10
    periodSeconds: 15

persistence:
  enabled: true
  size: "8Gi"
  storageClassName: "local-path"
  # When using local-path-provisioner, the volume is mounted with root permissions.
  # We need to run an init container as root to chown the volume to the jenkins user (1000).
  securityContext:
    runAsUser: 0
    fsGroup: 1000
