controller:
  admin:
    Username: admin
    Password: admin

  serviceType: NodePort
  nodePort: 30080

  image:
    repository: "dubithal/k8s-jenkins-controller" 
    tag: "latest"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean

  initContainer:
    command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home && echo 'Permissions fixed'"]
    securityContext:
      runAsUser: 0
